### ISSUE TITLE
FIXME: Flake.nix: Failure to build due to headless-chrome. 

### ISSUE THREAD

**Issue by ealtun21** [KUACC-VALAR-HPC-KOC-UNIVERSITY/kuvpn#1]
TLDR Logs:
```
warning: Git tree '/home/nyverin/Documents/kuvpn' is dirty
error: builder for '/nix/store/va2lg7a0dkss0c6w96ihijhyvl2vrw16-kuvpn-0.6.2.drv' failed with exit code 101;
       last 10 log lines:
       >    Compiling tungstenite v0.24.0
       > error: failed to run custom build command for `headless_chrome v1.0.14`
       >
       > Caused by:
       >   process didn't exit successfully: `/build/j012x5pg4mvwylpmi0jg16p354sv13xd-source/target/release/build/headless_chrome-cf64121cc147832e/build-script-build` (exit status: 101)
       >   --- stderr
       >   thread 'main' panicked at /build/cargo-vendor-dir/auto_generate_cdp-0.4.4/src/lib.rs:116:61:
       >   called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
       >   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/va2lg7a0dkss0c6w96ihijhyvl2vrw16-kuvpn-0.6.2.drv'.
 ```
 
 FULL LOGS:
 ```
 sourcing setup hook '/nix/store/h05y62lqg5cj9p8bvkd3al6h78zccnd1-cargo-build-hook.sh/nix-support/setup-hook'
sourcing setup hook '/nix/store/sijfvqmybvb0814wa3zg1w7asl3v1ns8-cargo-check-hook.sh/nix-support/setup-hook'
sourcing setup hook '/nix/store/wsax715m0q7j32dcz8wfl14628ypg43l-cargo-install-hook.sh/nix-support/setup-hook'
sourcing setup hook '/nix/store/b2n79s0vfxq86drqyk5808gfini5c4z1-cargo-setup-hook.sh/nix-support/setup-hook'
sourcing setup hook '/nix/store/dv5vgsw8naxnkcc88x78vprbnn1pp44y-patchelf-0.15.0/nix-support/setup-hook'
sourcing setup hook '/nix/store/i4iynx9axbq23sd0gyrc5wdb46zz6z8l-update-autotools-gnu-config-scripts-hook/nix-support/setup-hook'
sourcing setup hook '/nix/store/h9lc1dpi14z7is86ffhl3ld569138595-audit-tmpdir.sh'
sourcing setup hook '/nix/store/m54bmrhj6fqz8nds5zcj97w9s9bckc9v-compress-man-pages.sh'
sourcing setup hook '/nix/store/wgrbkkaldkrlrni33ccvm3b6vbxzb656-make-symlinks-relative.sh'
sourcing setup hook '/nix/store/5yzw0vhkyszf2d179m0qfkgxmp5wjjx4-move-docs.sh'
sourcing setup hook '/nix/store/fyaryjvghbkpfnsyw97hb3lyb37s1pd6-move-lib64.sh'
sourcing setup hook '/nix/store/kd4xwxjpjxi71jkm6ka0np72if9rm3y0-move-sbin.sh'
sourcing setup hook '/nix/store/pag6l61paj1dc9sv15l7bm5c17xn5kyk-move-systemd-user-units.sh'
sourcing setup hook '/nix/store/jivxp510zxakaaic7qkrb7v1dd2rdbw9-multiple-outputs.sh'
sourcing setup hook '/nix/store/ilaf1w22bxi6jsi45alhmvvdgy4ly3zs-patch-shebangs.sh'
sourcing setup hook '/nix/store/cickvswrvann041nqxb0rxilc46svw1n-prune-libtool-files.sh'
sourcing setup hook '/nix/store/xyff06pkhki3qy1ls77w10s0v79c9il0-reproducible-builds.sh'
sourcing setup hook '/nix/store/aazf105snicrlvyzzbdj85sx4179rpfp-set-source-date-epoch-to-latest.sh'
sourcing setup hook '/nix/store/gps9qrh99j7g02840wv5x78ykmz30byp-strip.sh'
sourcing setup hook '/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/nix-support/setup-hook'
sourcing setup hook '/nix/store/pg90p34kys2famxnq7925sbgj4jrnsi8-binutils-wrapper-2.42/nix-support/setup-hook'
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/zfhqz0fghi9r9avwn9c16i9453c927s5-j012x5pg4mvwylpmi0jg16p354sv13xd-source
calling 'unpackCmd' function hook '_defaultUnpack' /nix/store/zfhqz0fghi9r9avwn9c16i9453c927s5-j012x5pg4mvwylpmi0jg16p354sv13xd-source
source root is j012x5pg4mvwylpmi0jg16p354sv13xd-source
evaling implicit 'postUnpack' string hook
calling 'postUnpack' function hook 'cargoSetupPostUnpackHook'
Executing cargoSetupPostUnpackHook
Finished cargoSetupPostUnpackHook
calling 'postUnpack' function hook '_updateSourceDateEpochFromSourceRoot'
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
calling 'postPatch' function hook 'cargoSetupPostPatchHook'
Executing cargoSetupPostPatchHook
Validating consistency between /build/j012x5pg4mvwylpmi0jg16p354sv13xd-source/Cargo.lock and /build/cargo-vendor-dir/Cargo.lock
Finished cargoSetupPostPatchHook
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
calling 'preConfigure' function hook '_multioutConfig'
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
Executing cargoBuildHook
++ env CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/bin/cc CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/bin/cc CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu HOST_CC=/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/bin/cc HOST_CXX=/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/bin/c++ cargo build -j 16 --target x86_64-unknown-linux-gnu --offline --profile release
warning: `/build/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
warning: `/build/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
   Compiling libc v0.2.155
   Compiling proc-macro2 v1.0.86
   Compiling unicode-ident v1.0.12
   Compiling cfg-if v1.0.0
   Compiling version_check v0.9.5
   Compiling typenum v1.17.0
   Compiling pkg-config v0.3.30
   Compiling rustls v0.23.12
   Compiling serde v1.0.204
   Compiling subtle v2.6.1
   Compiling tinyvec_macros v0.1.1
   Compiling spin v0.9.8
   Compiling untrusted v0.9.0
   Compiling rustls-pki-types v1.8.0
   Compiling byteorder v1.5.0
   Compiling tinyvec v1.8.0
   Compiling memchr v2.7.4
   Compiling serde_json v1.0.127
   Compiling log v0.4.22
   Compiling ident_case v1.0.1
   Compiling fnv v1.0.7
   Compiling adler2 v2.0.0
   Compiling percent-encoding v2.3.1
   Compiling unicode-bidi v0.3.15
   Compiling strsim v0.11.1
   Compiling once_cell v1.19.0
   Compiling form_urlencoded v1.2.1
   Compiling miniz_oxide v0.8.0
   Compiling crc32fast v1.4.2
   Compiling generic-array v0.14.7
   Compiling zeroize v1.8.1
   Compiling webpki-roots v0.26.5
   Compiling itoa v1.0.11
   Compiling auto_generate_cdp v0.4.4
   Compiling regex-syntax v0.8.4
   Compiling aho-corasick v1.1.3
   Compiling base64 v0.22.1
   Compiling flate2 v1.0.33
   Compiling ryu v1.0.18
   Compiling unicode-normalization v0.1.23
   Compiling quote v1.0.36
   Compiling cpufeatures v0.2.13
   Compiling thiserror v1.0.63
   Compiling zstd-safe v7.2.1
   Compiling syn v2.0.72
   Compiling jobserver v0.1.32
   Compiling getrandom v0.2.15
   Compiling socks v0.3.4
   Compiling utf8parse v0.2.2
   Compiling rustix v0.38.34
   Compiling anstyle-parse v0.2.5
   Compiling rand_core v0.6.4
   Compiling powerfmt v0.2.0
   Compiling cc v1.1.7
   Compiling idna v0.5.0
   Compiling anstyle-query v1.1.1
   Compiling bitflags v2.6.0
   Compiling is_terminal_polyfill v1.70.1
   Compiling anstyle v1.0.8
   Compiling colorchoice v1.0.2
   Compiling linux-raw-sys v0.4.14
   Compiling crc-catalog v2.4.0
   Compiling httparse v1.9.4
   Compiling convert_case v0.4.0
   Compiling crc v3.2.1
   Compiling deranged v0.3.11
   Compiling anstream v0.6.15
   Compiling rustls-pemfile v2.1.3
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.4
   Compiling url v2.5.2
   Compiling digest v0.10.7
   Compiling inout v0.1.3
   Compiling cipher v0.4.4
   Compiling time-core v0.1.2
   Compiling hashbrown v0.14.5
   Compiling hmac v0.12.1
   Compiling sha1 v0.10.6
   Compiling bumpalo v3.16.0
   Compiling bytes v1.6.1
   Compiling option-ext v0.2.0
   Compiling openssl-probe v0.1.5
   Compiling equivalent v1.0.1
   Compiling num-conv v0.1.0
   Compiling lockfree-object-pool v0.1.6
   Compiling anyhow v1.0.86
   Compiling zip v2.2.0
   Compiling simd-adler32 v0.3.7
   Compiling regex-automata v0.4.7
   Compiling time v0.3.36
   Compiling zopfli v0.8.1
   Compiling http v1.1.0
   Compiling rustls-native-certs v0.7.3
   Compiling dirs-sys v0.4.1
   Compiling indexmap v2.5.0
   Compiling aes v0.8.4
   Compiling pbkdf2 v0.12.2
   Compiling lzma-rs v0.3.0
   Compiling ring v0.17.8
   Compiling zstd-sys v2.0.13+zstd.1.5.6
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling utf-8 v0.7.6
   Compiling data-encoding v2.6.0
   Compiling heck v0.5.0
   Compiling home v0.5.9
   Compiling constant_time_eq v0.3.1
   Compiling either v1.13.0
   Compiling fastrand v2.1.1
   Compiling same-file v1.0.6
   Compiling deflate64 v0.1.9
   Compiling clap_lex v0.7.2
   Compiling tempfile v3.12.0
   Compiling walkdir v2.5.0
   Compiling which v6.0.3
   Compiling clap_builder v4.5.11
   Compiling directories v5.0.1
   Compiling darling_core v0.20.10
   Compiling lazy_static v1.5.0
   Compiling humantime v2.1.0
   Compiling colored v2.1.0
   Compiling regex v1.10.6
   Compiling env_filter v0.1.2
   Compiling env_logger v0.11.5
   Compiling serde_derive v1.0.204
   Compiling zerocopy-derive v0.7.35
   Compiling zeroize_derive v1.4.2
   Compiling thiserror-impl v1.0.63
   Compiling displaydoc v0.2.5
   Compiling clap_derive v4.5.11
   Compiling bzip2 v0.4.4
   Compiling zerocopy v0.7.35
   Compiling rustls-webpki v0.102.6
   Compiling darling_macro v0.20.10
   Compiling darling v0.20.10
   Compiling ppv-lite86 v0.2.20
   Compiling derive_builder_core v0.20.1
   Compiling rand_chacha v0.3.1
   Compiling rand v0.8.5
   Compiling clap v4.5.11
   Compiling derive_builder_macro v0.20.1
   Compiling derive_builder v0.20.1
   Compiling ureq v2.10.1
   Compiling headless_chrome v1.0.14
   Compiling tungstenite v0.24.0
error: failed to run custom build command for `headless_chrome v1.0.14`

Caused by:
  process didn't exit successfully: `/build/j012x5pg4mvwylpmi0jg16p354sv13xd-source/target/release/build/headless_chrome-cf64121cc147832e/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /build/cargo-vendor-dir/auto_generate_cdp-0.4.4/src/lib.rs:116:61:
  called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by ealtun21** [comment]
Issue seems to be due to nix not having **rustfmt** included in the rustbuilder. Testing new flake.nix. For anyone who may get this issue, make sure **rustfmt** is installed. If you installed rust via rustup, it should be installed. If you installed just cargo via something brew, you'd also need to install rustfmt.
